---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/user":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/login":
    post:
      summary: login user
      responses:
        '200':
          description: successful
  "/auto_login":
    get:
      summary: auto_login user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
